spring:
  application:
    name: test-app
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    location:  classpath:db/migration
    enabled: false

logging:
  level:
    org:
      flyway:
        core: TRACE
      hibernate:
        sql: TRACE




